CREATE TABLE lei."TBL_USUARIO"
(
  "US_CODIGO" integer NOT NULL,
  "US_NOME" character varying(40) NOT NULL,
  "US_CPF" character varying(14) NOT NULL,
  "US_SEXO" character varying(20),
  "US_TELEFONE" character varying(16),
  "US_DATA_CADASTRO" date NOT NULL,
  "US_CIDADE" character varying(40),
  "US_EMAIL" character varying(100) NOT NULL,
  "US_SENHA" character varying(32) NOT NULL,
  CONSTRAINT "PK_USUARIO" PRIMARY KEY ("US_CODIGO"),
  CONSTRAINT "UNIQUE_CPF" UNIQUE ("US_CPF"),
  CONSTRAINT "UNIQUE_EMAIL" UNIQUE ("US_EMAIL")
);

CREATE TABLE lei."TBL_PRODUTO"
(
  "PR_CODIGO" integer NOT NULL,
  "PR_NOME" character varying(40) NOT NULL,
  "PR_DESCRICAO" character varying(500),
  "PR_PRECO" money NOT NULL,
  "PR_NOVO" boolean NOT NULL,
  "PR_DATA_FIM" date NOT NULL,
  "US_CODIGO_USUARIO" integer NOT NULL,
  CONSTRAINT "PK_PRODUTO" PRIMARY KEY ("PR_CODIGO"),
  CONSTRAINT "FK_PRODUTO_USUARIO" FOREIGN KEY ("US_CODIGO_USUARIO")
      REFERENCES lei."TBL_USUARIO" ("US_CODIGO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE lei."TBL_LANCE"
(
  "LA_CODIGO" integer NOT NULL,
  "PR_CODIGO_PRODUTO" integer NOT NULL,
  "US_CODIGO_USUARIO" integer NOT NULL,
  "LA_DATA_CRIACAO" date NOT NULL,
  CONSTRAINT "PK_LANCE" PRIMARY KEY ("LA_CODIGO"),
  CONSTRAINT "FK_LANCE_PRODUTO" FOREIGN KEY ("PR_CODIGO_PRODUTO")
      REFERENCES lei."TBL_PRODUTO" ("PR_CODIGO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_LANCE_USUARIO" FOREIGN KEY ("US_CODIGO_USUARIO")
      REFERENCES lei."TBL_USUARIO" ("US_CODIGO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)